### ISSUE TITLE
Hiscores

### ISSUE THREAD

**Issue by iBunney237** [open-osrs/plugin-hosting#11]
Hello,

Once i look up someone or myself every boss kill count is moved one to the right.

For example i have 734 sire kc, but when i look up myself it says that i have 0 sire kc and 734 hydra kc.

Any ideas?

**Comment by ThatGamerBlue** [comment]
duplicate and wrong repo

**Comment by iBunney237** [comment]
im sorry, could you explain a bit more how to fix it?

I didnt instal any new plugins, it just started to be like that once i logged in couple days ago.
